variables:
  DEVELOPER_DIR: "/Applications/Xcode_9.3.1.app"
jobs:
- job: build_osx
  pool:
    vmImage: 'macOS-10.13'
  timeoutInMinutes: 120
  steps:
# ここで、各サブモジュールのビルド済みバイナリをDL
# なければビルド
# また、FORCE_BUILDが指定されているときは、DLしない
# ------------------------------------------ 
# 別の script では、ディレクトリ位置や環境変数のexportは保存されない（別のbashが起動される）
# 環境変数を受け渡すには、先のscriptで
# `echo '##vso[task.setvariable variable=<varname>]<value>'`
# を実行し、続くscriptで
# `env: { varname: $<varname> }`
# を指定する
  - script: brew install libtool automake
    displayName: brew install
  - script: git submodule update --init
  - script: |
      WXWIDGETS_HASH1=$(cd ./ext/wxWidgets && git rev-parse HEAD)
      echo "##vso[task.setvariable variable=wxwidgets_hash1]$WXWIDGETS_HASH1"
      echo "##vso[task.setvariable variable=wxwidgets_hash2]$(cd ./ext/wxWidgets && git rev-parse HEAD)"
    displayName: listup hashes
  - script: cd gradle && ./gradlew update_submodules
    displayName: update submodues
  - script: printenv
    env: { 
      WXWIDGETS_HASH1: $WXWIDGETS_HASH1,
      WXWIDGETS_HASH2: $WXWIDGETS_HASH2
    }
    displayName: printenv
  - bash: "cd $(System.DefaultWorkingDirectory)/Terra && echo execute bash script && printenv && pwd"
    displayName: printenv2
  - script: cd gradle && ./gradlew build_all -Pconfig=Release
    displayName: build_all
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/build_release/Release'
      artifactName: Binary
- job: deploy
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: "Download Artifacts"
    inputs:
      artifactName: Binary
  dependsOn: build_osx
  condition: succeeded()
